config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"

  get "/auth/twitter", as: :login
  get "/logout", to: "sessions#destroy"
  get "/auth/twitter/callback", to: "sessions#create"
  get "/profile", to: "users#show"
  post 'unfollow', to: 'users#unfollow'
  post 'favorites', to: 'users#favorite'
  post 'replies', to: 'users#reply'

  resources :tweets, only: [:create]
  post 'retweets', to: 'tweets#retweet'

end

app/models/user.rb
class User < ActiveRecord::Base

  def self.from_omniauth(auth_info)
    user = User.find_or_create_by(uid: auth_info.uid)

    user.update_attributes(
      screen_name:        auth_info.info.nickname,
      name:               auth_info.info.name,
      email:              auth_info.info.email,
      location:           auth_info.info.location,
      image:              auth_info.info.image,
      description:        auth_info.info.description,
      urls:               auth_info.info.urls,
      oauth_token:        auth_info.credentials.token,
      oauth_token_secret: auth_info.credentials.secret
    )
    user
  end

  def twitter_client
    @connection ||= Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV["twitter_publishable_key"]
      config.consumer_secret     = ENV["twitter_secret_key"]
      config.access_token        = oauth_token
      config.access_token_secret = oauth_token_secret
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
      redirect_to profile_path
    else
      redirect_to root_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def create
    current_user.twitter_client.update(params[:tweet])
    redirect_to profile_path
  end

  def retweet
    current_user.twitter_client.retweet(params[:tweet_id])
    redirect_to profile_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user.twitter_client.user
    @feed = current_user.twitter_client.home_timeline
  end

  def unfollow
    current_user.twitter_client.unfollow(params[:user_id].to_i)
    redirect_to :back
  end

  def favorite
    current_user.twitter_client.favorite(params[:tweet_id])
    redirect_to :back
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="row">
    <div class="col-lg-12 text-center" id="copyright">
      <p>Copyright &copy; ChatterBox 2015</p>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top"
     role="navigation"
     id="navbar-flash">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button"
                    class="navbar-toggle"
                    data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "ChatterBox", root_path, class: "navbar-brand" %>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <% if current_user %>
        <ul class="nav navbar-nav">
          <li><%= link_to "Feed", profile_path %><span class="sr-only">(current)</span></a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right" id="navbar">
          <li>
            <a href="/profile"><%= "Hello, #{current_user.name}" %></a>
          </li>
          <li>
            <%= link_to "Logout", logout_path %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
  <title>ChatterBoxes</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: 'layouts/navbar' %>

  <%= yield %>

  <%= render partial: 'layouts/footer' %>
</body>
</html>

app/views/users/_feed.html.erb
<h1>Latest Tweets</h1>
<br>
  <div class="card-columns">
    <% @feed.each do |tweet| %>
    <div class="card card-block" style="background-color: #E5FFFF; border-color: #C9C9C9;">
      <h4 class="card-title">
        <%= image_tag tweet.user.profile_image_url %>
        <span><strong>@<%= link_to tweet.user.screen_name, "https://twitter.com/#{tweet.user.screen_name}" %></span></strong>
      </div>
    </h4>
    <div class="card-text" style="background-color: #FFFFFF; border-color: #C9C9C9;">
        <p><%= tweet.full_text %></p>
        <span class="favorite"><%= link_to(favorites_path(tweet_id: tweet.id), method: :post) do %></span>
          <span class="glyphicon glyphicon-star-empty" style="padding: 20px"> <%= tweet.favorite_count%></span>
        <% end %>
        <span class="retweet"><%= link_to(retweets_path(tweet_id: tweet.id), method: :post) do %></span>
          <span class="glyphicon glyphicon-retweet" style="padding: 20px"> <%= tweet.retweet_count%></span>
        <% end %>
        <span class="unfollow" style="padding: 20px"><%= link_to("Unfollow", unfollow_path(user_id: tweet.user.id), method: :post) %></span>
    <% end %>
    </div>
   </div>
  </div>

app/views/users/_profile.html.erb
<br>
<br>
<br>
<br>
<div class="card card-block" style="background-color: #E5FFFF; border-color: #333">
  <h4 class="card-title">
    <%= image_tag @user.profile_image_url %>
    <span><strong>@<%= link_to @user.screen_name, "https://twitter.com/#{@user.screen_name}" %></strong></span>
</div>
<p blockquote class="card-blockquote" style="border-color: #333;">
  <h5>
    <ul>
      <span style="padding: 20px">Tweets: <%= @user.tweets_count %></span>
      <span style="padding: 20px">Following: <%= @user.friends_count %></span>
      <span style="padding: 20px">Followers: <%= @user.followers_count %></span>
    </ul>
    <ul>
      <span style="padding: 20px">Description: <%= @user.description %></span>
      <span style="padding: 20px">Location: <%= @user.location %></span>
    </ul>
  </h5>
</p>

app/views/users/_tweet.html.erb
<br>
<div class="card card-block" id="tweet">
  <%= form_for :tweet, url: tweets_path do |f| %>
    <fieldset>
      <div class="form-group">
        <label for="textArea" class="col-lg-2 control-label">New Tweet</label>
        <div class="col-lg-10">
          <textarea name="tweet" class="form-control control" rows="3"></textarea>
        </div>
          <%= f.submit "Tweet!", class: "btn btn-primary" %></span>
      </div>
    </fieldset>
  <% end %>
</div>

app/views/users/show.html.erb
<section id="intro" class="intro-section">
  <div class="row col-md-12">
    <div class="col-md-5 col-xs-offset-1">
      <%= render partial: 'profile' %>
      <%= render partial: 'tweet' %>
    </div>
    <div class="col-md-5">
      <%= render partial: 'feed' %>
    </div>
  </div>
</section>

app/views/welcome/index.html.erb
<section id="intro" class="intro-section">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <% if current_user %>
          <h1><p>Hello, <%= link_to current_user.name, profile_path %></p></h1>
          <% else %>
              <h1>Welcome to ChatterBox. Let out your inner Chatty Cathy.</h1>
              <h1><%= link_to "Sign in with Twitter", login_path %></h1>
          <% end %>
      </div>
    </div>
  </div>
</section>